Repository m1naworld/hanghae-soundsea-api, pull requests merged in 2022-12, with the labels that each got.

#2 ✨ Feat: common 패키지 작성
  src/main/java/com/sparta/soundsea/common/entity/Timestamped.java
  src/main/java/com/sparta/soundsea/common/exception/ExceptionMessage.java
  src/main/java/com/sparta/soundsea/common/exception/ExceptionResponse.java
  src/main/java/com/sparta/soundsea/common/response/DataResponse.java
  src/main/java/com/sparta/soundsea/common/response/Response.java
  src/main/java/com/sparta/soundsea/common/response/ResponseMessage.java
Labels: feature

#7 ♻️ Refactor: PR 템플릿 이모지 추가
  .github/PULL_REQUEST_TEMPLATE.md
Labels: refactor

#9 ✨ Feat: Spring Security 초기 기본 설정
  build.gradle
  src/main/java/com/sparta/soundsea/security/WebSecurityConfig.java
Labels: feature

#14 ✨ Feat: 도메인별 entity 생성 및 연관관계 설정
  src/main/java/com/sparta/soundsea/comment/entity/Comment.java
  src/main/java/com/sparta/soundsea/music/entity/Music.java
  src/main/java/com/sparta/soundsea/user/entity/User.java
Labels: feature

#19 ✨ Feat: Comment API, Error Code 등록
  src/main/java/com/sparta/soundsea/comment/controller/CommentController.java
  src/main/java/com/sparta/soundsea/comment/dto/CommentRequestDto.java
  src/main/java/com/sparta/soundsea/comment/dto/CommentResponseDto.java
  src/main/java/com/sparta/soundsea/comment/repository/CommentRepository.java
  src/main/java/com/sparta/soundsea/comment/service/CommentService.java
  src/main/java/com/sparta/soundsea/common/exception/ExceptionMessage.java
Labels: feature

#23 ✨ Feat: User Domain 기능 구현
  .gitignore
  src/main/java/com/sparta/soundsea/comment/entity/Comment.java
  src/main/java/com/sparta/soundsea/common/exception/ExceptionMessage.java
  src/main/java/com/sparta/soundsea/common/response/ResponseMessage.java
  src/main/java/com/sparta/soundsea/music/entity/Music.java
  src/main/java/com/sparta/soundsea/user/controller/UserController.java
  src/main/java/com/sparta/soundsea/user/dto/LoginUserDto.java
  src/main/java/com/sparta/soundsea/user/dto/RequestLoginUserDto.java
  src/main/java/com/sparta/soundsea/user/dto/RequestSignUpUserDto.java
  src/main/java/com/sparta/soundsea/user/dto/SignUpUserDto.java
  src/main/java/com/sparta/soundsea/user/entity/User.java
  src/main/java/com/sparta/soundsea/user/exception/LoginExceptionHandler.java
  src/main/java/com/sparta/soundsea/user/exception/SignUpExceptionHandler.java
  src/main/java/com/sparta/soundsea/user/mapper/UserMapper.java
  src/main/java/com/sparta/soundsea/user/service/UserService.java
  src/main/java/com/sparta/soundsea/user/service/Validator.java
Labels: good first issue, feature

#25 ✨ Feat: application.properties 설정
  src/main/resources/application.properties
Labels: feature

#27 ✨ Feat: Jwt 기능 구현
  build.gradle
  src/main/java/com/sparta/soundsea/common/exception/ExceptionMessage.java
  src/main/java/com/sparta/soundsea/common/response/Response.java
  src/main/java/com/sparta/soundsea/security/WebSecurityConfig.java
  src/main/java/com/sparta/soundsea/security/jwt/JwtAuthFilter.java
  src/main/java/com/sparta/soundsea/security/jwt/JwtUtil.java
  src/main/java/com/sparta/soundsea/security/jwt/exception/CustomSecurityException.java
  src/main/java/com/sparta/soundsea/security/jwt/exception/JwtExceptionHandlerFilter.java
  src/main/java/com/sparta/soundsea/user/controller/UserController.java
  src/main/java/com/sparta/soundsea/user/service/UserService.java
Labels: good first issue, feature

#28 ✨ Feat: mysql 관련 의존성 추가 및 설정
  .gitignore
  build.gradle
  src/main/java/com/sparta/soundsea/comment/entity/Comment.java
  src/main/resources/application.properties
Labels: feature

#29 ✨ Feat : Music [POST] 작성
  src/main/java/com/sparta/soundsea/common/response/ResponseMessage.java
  src/main/java/com/sparta/soundsea/music/controller/MusicController.java
  src/main/java/com/sparta/soundsea/music/dto/RequestCreateMusic.java
  src/main/java/com/sparta/soundsea/music/dto/RequestPageMusic.java
  src/main/java/com/sparta/soundsea/music/dto/ResponseMusic.java
  src/main/java/com/sparta/soundsea/music/dto/ResponsePageMusic.java
  src/main/java/com/sparta/soundsea/music/entity/Music.java
  src/main/java/com/sparta/soundsea/music/exception/MusicExceptionHandler.java
  src/main/java/com/sparta/soundsea/music/mapper/MusicMapper.java
  src/main/java/com/sparta/soundsea/music/repository/MusicRepository.java
  src/main/java/com/sparta/soundsea/music/service/MusicService.java
Labels: feature

#31 ✨ Feat: 댓글 controller,dto 설정
  src/main/java/com/sparta/soundsea/comment/controller/CommentController.java
  src/main/java/com/sparta/soundsea/comment/dto/CommentResponseDto.java
  src/main/java/com/sparta/soundsea/comment/service/CommentService.java
  src/main/java/com/sparta/soundsea/common/exception/ExceptionMessage.java
  src/main/java/com/sparta/soundsea/common/response/ResponseMessage.java
Labels: feature

#35 ✨ Feat : Music 도메인 GET 기능 추가(Feature/#30)
  src/main/java/com/sparta/soundsea/comment/repository/CommentRepository.java
  src/main/java/com/sparta/soundsea/music/controller/MusicController.java
  src/main/java/com/sparta/soundsea/music/dto/ResponseMusic.java
  src/main/java/com/sparta/soundsea/music/mapper/MusicMapper.java
  src/main/java/com/sparta/soundsea/music/repository/MusicRepository.java
  src/main/java/com/sparta/soundsea/music/service/MusicService.java
  src/main/java/com/sparta/soundsea/security/WebSecurityConfig.java
Labels: feature

#38 ✨ Feat: Cors 설정
  build.gradle
  src/main/java/com/sparta/soundsea/security/WebSecurityConfig.java
Labels: feature

#39 ✨ Feat: RefreshToken 만료 시 예외 처리 추가
  .gitignore
  src/main/java/com/sparta/soundsea/common/exception/ExceptionMessage.java
  src/main/java/com/sparta/soundsea/common/response/ResponseMessage.java
  src/main/java/com/sparta/soundsea/security/jwt/JwtAuthFilter.java
  src/main/java/com/sparta/soundsea/security/jwt/JwtUtil.java
Labels: bug

#40 ♻️ Refactor: cors 설정 코드 변경
  src/main/java/com/sparta/soundsea/security/WebSecurityConfig.java
Labels: refactor

#44 ✨ Feat : Music 도메인 수정(PATCH), 삭제(DELETE) 기능 추가 (+ 오타수정)
  src/main/java/com/sparta/soundsea/music/controller/MusicController.java
  src/main/java/com/sparta/soundsea/music/entity/Music.java
  src/main/java/com/sparta/soundsea/music/service/MusicService.java
Labels: feature, refactor

#45 ✨ Feat: 댓글 CURD 작업 마무리
  src/main/java/com/sparta/soundsea/comment/controller/CommentController.java
  src/main/java/com/sparta/soundsea/comment/dto/CommentRequestDto.java
  src/main/java/com/sparta/soundsea/comment/dto/CommentResponseDto.java
  src/main/java/com/sparta/soundsea/comment/entity/Comment.java
  src/main/java/com/sparta/soundsea/comment/exception/CommentExceptionHandler.java
  src/main/java/com/sparta/soundsea/comment/mapper/CommentMapper.java
  src/main/java/com/sparta/soundsea/comment/repository/CommentRepository.java
  src/main/java/com/sparta/soundsea/comment/service/CommentService.java
Labels: feature

#49 🐛 Fix: 댓글 예외처리 handler 오류 수정
  src/main/java/com/sparta/soundsea/comment/controller/CommentController.java
  src/main/java/com/sparta/soundsea/comment/dto/CommentResponseDto.java
  src/main/java/com/sparta/soundsea/comment/exception/CommentExceptionHandler.java
  src/main/java/com/sparta/soundsea/comment/service/CommentService.java
  src/main/java/com/sparta/soundsea/music/service/MusicService.java
  src/main/resources/application.properties
Labels: bug, feature

#51 ♻️ Refactor : Music 도메인 예외 처리 리팩토링 (Feature/#47)
  build.gradle
  src/main/java/com/sparta/soundsea/music/exception/MusicExceptionHandler.java
  src/main/java/com/sparta/soundsea/music/service/MusicService.java
Labels: refactor

#53 🐛 Fix: cors 설정 추가
  src/main/java/com/sparta/soundsea/security/WebSecurityConfig.java
Labels: bug

#58 ♻️ Refactor: ExceptionMessage 수정
  src/main/java/com/sparta/soundsea/common/exception/ExceptionMessage.java
  src/main/resources/application.properties
Labels: refactor

#60 ✨ Feat: Naver OAuth 기능
  .gitignore
  src/main/java/com/sparta/soundsea/security/WebSecurityConfig.java
  src/main/java/com/sparta/soundsea/security/jwt/JwtAuthFilter.java
  src/main/java/com/sparta/soundsea/user/controller/NaverOauth.java
  src/main/java/com/sparta/soundsea/user/controller/UserController.java
  src/main/java/com/sparta/soundsea/user/dto/NaverLoginDto.java
  src/main/java/com/sparta/soundsea/user/dto/RequestNaverOauthLoginDto.java
  src/main/java/com/sparta/soundsea/user/dto/RequestNaverOauthTokenDto.java
  src/main/java/com/sparta/soundsea/user/dto/RequestSignUpUserDto.java
  src/main/java/com/sparta/soundsea/user/mapper/UserMapper.java
  src/main/java/com/sparta/soundsea/user/service/UserNaverService.java
Labels: good first issue, feature

#61 ♻️ Refactor : Music 로그인 여부 T/F 반환 추가, Music&Comment 작성 유저 확인 여부 True, False 반환 추가
  src/main/java/com/sparta/soundsea/comment/dto/CommentResponseDto.java
  src/main/java/com/sparta/soundsea/common/response/DataResponse.java
  src/main/java/com/sparta/soundsea/music/controller/MusicController.java
  src/main/java/com/sparta/soundsea/music/dto/ResponseMusic.java
  src/main/java/com/sparta/soundsea/music/mapper/MusicMapper.java
  src/main/java/com/sparta/soundsea/music/service/MusicService.java
Labels: feature, refactor

#62 ♻️ Refactor: 댓글작성 본인 여부 예외처리 추가, checkLoginId - > checkLogin 변경
  src/main/java/com/sparta/soundsea/comment/controller/CommentController.java
  src/main/java/com/sparta/soundsea/common/response/DataResponse.java
  src/main/java/com/sparta/soundsea/music/controller/MusicController.java
Labels: feature, refactor

#65 ✨ Feat : Music 수정(PATCH) 기능 추가
  src/main/java/com/sparta/soundsea/music/entity/Music.java
  src/main/java/com/sparta/soundsea/music/service/MusicService.java
Labels: feature

#67 ♻️ Refactor: 토큰 없을 시 예외처리에 대한 오류 수정
  src/main/java/com/sparta/soundsea/comment/exception/CommentExceptionHandler.java
Labels: refactor

#73 🐛 Fix: NaverOauth Login 시 redirect 되지 않는 현상 수정
  src/main/java/com/sparta/soundsea/user/controller/UserController.java
Labels: bug

#77 ♻️ Refactor: common패키지 및 kakaoLogin 안쓰는 코드 및 주석 정리
  src/main/java/com/sparta/soundsea/common/exception/ExceptionMessage.java
  src/main/java/com/sparta/soundsea/common/response/DataResponse.java
  src/main/java/com/sparta/soundsea/common/response/Response.java
  src/main/java/com/sparta/soundsea/user/service/UserKakaoService.java
  src/main/java/com/sparta/soundsea/user/service/UserService.java
Labels: refactor

#78 ♻️ Refactor: Security, User 도메인 필요 없는 메소드 및 주석 등 삭제
  src/main/java/com/sparta/soundsea/security/WebSecurityConfig.java
  src/main/java/com/sparta/soundsea/user/controller/UserController.java
  src/main/java/com/sparta/soundsea/user/dto/RequestLoginUserDto.java
  src/main/java/com/sparta/soundsea/user/service/UserNaverService.java
  src/main/java/com/sparta/soundsea/user/service/UserService.java
Labels: refactor

#81 ♻️ Refactor : 미사용 파일 및 코드, 주석 삭제
  src/main/java/com/sparta/soundsea/music/controller/MusicController.java
  src/main/java/com/sparta/soundsea/music/dto/RequestPageMusic.java
  src/main/java/com/sparta/soundsea/music/dto/ResponsePageMusic.java
  src/main/java/com/sparta/soundsea/music/entity/Music.java
  src/main/java/com/sparta/soundsea/music/mapper/MusicMapper.java
  src/main/java/com/sparta/soundsea/music/service/MusicService.java
Labels: refactor

#80 ♻️ Refactor: comment정리 및 이미지S3 버켓에 저장 기능 구현
  build.gradle
  src/main/java/com/sparta/soundsea/comment/controller/CommentController.java
  src/main/java/com/sparta/soundsea/comment/service/CommentService.java
  src/main/java/com/sparta/soundsea/image/config/S3Config.java
  src/main/java/com/sparta/soundsea/image/service/S3UploaderService.java
  src/main/java/com/sparta/soundsea/music/controller/MusicController.java
  src/main/java/com/sparta/soundsea/music/mapper/MusicMapper.java
  src/main/java/com/sparta/soundsea/music/service/MusicService.java
  src/main/resources/application.properties
Labels: refactor

#83 ♻️ Refactor: 프린트 구문 삭제
  src/main/java/com/sparta/soundsea/security/CustomUserDetailsService.java
  src/main/java/com/sparta/soundsea/security/jwt/JwtUtil.java
Labels: refactor
